name: runs-ttbot
on:
  schedule:
  - cron: '* * * * *'
jobs:
  build:
    runs-on: ubunto-latest
    steps:
      - name: sets up python
        uses: action/setup-python@v4
        with:
            python-version: '3.8'
          
      - name: installing stuff
        run:
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
      - name: executing python script
        env:
            ACCESS_TOKEN: ${{ secrets.DQD_ACCESS_TOKEN }}
            ACCESS_TOKEN_SECRET: ${{ secrets.DQD_ACCESS_TOKEN_SECRET }}
            CONSUMER_KEY: ${{ secrets.DQD_CONSUMER_KEY }}
            CONSUMER_SECRET: ${{ secrets.DQD_CONSUMER_SECRET }}
        run: python main.py
          
          
          
          

